export enum NotificationActionType {
  START_SET_NOTIFICATION = "START_SET_NOTIFICATION",
  SUCCESS_SET_NOTIFICATION = "SUCCESS_SET_NOTIFICATION",
  ERROR_SET_NOTIFICATION = "ERRROR_SET_NOTIFICATION",
  START_SET_NOTIFICATIONS = "START_SET_NOTIFICATIONS",
  SUCCESS_SET_NOTIFICATIONS = "SUCCESS_SET_NOTIFICATIONS",
  ERROR_SET_NOTIFICATIONS = "ERRROR_SET_NOTIFICATIONS",
}
