export enum UserActionType {
  SET_USER_START = "SET_USER_START",
  SET_USER_FALIED = "SET_USER_FALIED",
  SET_USER_SUCCESS = "SET_USER_SUCCESS",
  LOGOUT_USER = "LOGOUT_USER",
  SET_FOUND_USER_START = "SET_FOUND_USER_START",
  SET_FOUND_USER_FALIED = "SET_FOUND_USER_FALIED",
  SET_FOUND_USER_SUCCESS = "SET_FOUND_USER_SUCCESS",
  START_CHANGE_PASSWORD = "START_CHANGE_PASSWORD",
  ERROR_CHANGE_PASSWORD = "ERROR_CHANGE_PASSWORD",
  SUCCESS_CHANGE_PASSWORD = "SUCCESS_CHANGE_PASSWORD",
}
